import cdsapi

c = cdsapi.Client()

c.retrieve(
    'reanalysis-era5-single-levels',
    {
        'product_type': 'reanalysis',
        'format': 'grib',
        'variable': [
            '100m_u_component_of_wind', '100m_v_component_of_wind', '10m_u_component_of_neutral_wind',
            '10m_u_component_of_wind', '10m_v_component_of_neutral_wind', '10m_v_component_of_wind',
            '10m_wind_gust_since_previous_post_processing', '2m_dewpoint_temperature', '2m_temperature',
            'boundary_layer_height', 'clear_sky_direct_solar_radiation_at_surface', 'cloud_base_height',
            'convective_available_potential_energy', 'convective_inhibition', 'convective_precipitation',
            'convective_rain_rate', 'convective_snowfall', 'convective_snowfall_rate_water_equivalent',
            'downward_uv_radiation_at_the_surface', 'forecast_logarithm_of_surface_roughness_for_heat', 'geopotential',
            'high_cloud_cover', 'ice_temperature_layer_1', 'ice_temperature_layer_2',
            'ice_temperature_layer_3', 'ice_temperature_layer_4', 'instantaneous_10m_wind_gust',
            'instantaneous_large_scale_surface_precipitation_fraction', 'instantaneous_surface_sensible_heat_flux', 'k_index',
            'land_sea_mask', 'large_scale_precipitation', 'large_scale_precipitation_fraction',
            'large_scale_rain_rate', 'large_scale_snowfall', 'large_scale_snowfall_rate_water_equivalent',
            'low_cloud_cover', 'maximum_2m_temperature_since_previous_post_processing', 'maximum_total_precipitation_rate_since_previous_post_processing',
            'mean_sea_level_pressure', 'medium_cloud_cover', 'minimum_2m_temperature_since_previous_post_processing',
            'minimum_total_precipitation_rate_since_previous_post_processing', 'near_ir_albedo_for_diffuse_radiation', 'near_ir_albedo_for_direct_radiation',
            'precipitation_type', 'sea_surface_temperature', 'skin_temperature',
            'snow_albedo', 'snow_density', 'snow_depth',
            'snow_evaporation', 'snowfall', 'snowmelt',
            'surface_latent_heat_flux', 'surface_net_solar_radiation', 'surface_net_solar_radiation_clear_sky',
            'surface_net_thermal_radiation', 'surface_net_thermal_radiation_clear_sky', 'surface_pressure',
            'surface_sensible_heat_flux', 'surface_solar_radiation_downward_clear_sky', 'surface_solar_radiation_downwards',
            'surface_thermal_radiation_downward_clear_sky', 'surface_thermal_radiation_downwards', 'temperature_of_snow_layer',
            'toa_incident_solar_radiation', 'top_net_solar_radiation', 'top_net_solar_radiation_clear_sky',
            'top_net_thermal_radiation', 'top_net_thermal_radiation_clear_sky', 'total_cloud_cover',
            'total_column_cloud_ice_water', 'total_column_cloud_liquid_water', 'total_column_ozone',
            'total_column_rain_water', 'total_column_snow_water', 'total_column_supercooled_liquid_water',
            'total_column_water', 'total_column_water_vapour', 'total_precipitation',
            'total_sky_direct_solar_radiation_at_surface', 'total_totals_index', 'uv_visible_albedo_for_diffuse_radiation',
            'uv_visible_albedo_for_direct_radiation', 'vertical_integral_of_divergence_of_cloud_frozen_water_flux', 'vertical_integral_of_divergence_of_cloud_liquid_water_flux',
            'vertical_integral_of_divergence_of_geopotential_flux', 'vertical_integral_of_divergence_of_kinetic_energy_flux', 'vertical_integral_of_divergence_of_mass_flux',
            'vertical_integral_of_divergence_of_moisture_flux', 'vertical_integral_of_divergence_of_ozone_flux', 'vertical_integral_of_divergence_of_thermal_energy_flux',
            'vertical_integral_of_divergence_of_total_energy_flux', 'vertical_integral_of_eastward_cloud_frozen_water_flux', 'vertical_integral_of_eastward_cloud_liquid_water_flux',
            'vertical_integral_of_eastward_geopotential_flux', 'vertical_integral_of_eastward_heat_flux', 'vertical_integral_of_eastward_kinetic_energy_flux',
            'vertical_integral_of_eastward_mass_flux', 'vertical_integral_of_eastward_ozone_flux', 'vertical_integral_of_eastward_total_energy_flux',
            'vertical_integral_of_eastward_water_vapour_flux', 'vertical_integral_of_energy_conversion', 'vertical_integral_of_kinetic_energy',
            'vertical_integral_of_mass_of_atmosphere', 'vertical_integral_of_mass_tendency', 'vertical_integral_of_northward_cloud_frozen_water_flux',
            'vertical_integral_of_northward_cloud_liquid_water_flux', 'vertical_integral_of_northward_geopotential_flux', 'vertical_integral_of_northward_heat_flux',
            'vertical_integral_of_northward_kinetic_energy_flux', 'vertical_integral_of_northward_mass_flux', 'vertical_integral_of_northward_ozone_flux',
            'vertical_integral_of_northward_total_energy_flux', 'vertical_integral_of_northward_water_vapour_flux', 'vertical_integral_of_potential_and_internal_energy',
            'vertical_integral_of_potential_internal_and_latent_energy', 'vertical_integral_of_temperature', 'vertical_integral_of_thermal_energy',
            'vertical_integral_of_total_energy', 'vertically_integrated_moisture_divergence', 'zero_degree_level',
        ],
        'year': '2023',
        'month': '07',
        'day': [
            '01', '02', '03',
            '04', '05', '06',
            '07', '08', '09',
            '10', '11', '12',
            '13', '14', '15',
            '16', '17', '18',
            '19', '20', '21',
            '22', '23', '24',
            '25', '26', '27',
            '28', '29', '30',
            '31',
        ],
        'time': [
            '00:00', '06:00', '12:00',
            '18:00',
        ],
        'area': [
            52, 5, 42,
            16,
        ],
    },
    'download.grib')